const regions = {
  nairobi: [
    { id: '1', text: 'Bisil' },
    { id: '2', text: 'Dandora Dayspring/Terminus' },
    { id: '3', text: 'Fedha' },
    { id: '4', text: 'Gatundu' },
    { id: '5', text: 'Kajiado' },
    { id: '6', text: 'Kariobangi South' },
    { id: '7', text: 'Kasarani Sunton' },
    { id: '8', text: 'Kayole Masimba' },
    { id: '9', text: 'Kayole Mugendi' },
    { id: '10', text: 'Uthiru 87' },
  ],

  central: [
    { id: '1', text: 'Chuka' },
    { id: '2', text: 'Embu' },
    { id: '3', text: 'Isiolo Burapesa ' },
    { id: '4', text: 'Isiolo Soko Mjinga' },
    { id: '5', text: 'Karatina' },
    { id: '6', text: 'Kianjai' },
    { id: '7', text: 'Kirinyaga Sagana' },
    { id: '8', text: 'Maua Down Town' },
    { id: '9', text: 'Maua Kamuki' },
    { id: '10', text: 'Meru Gakoromone ' },
    { id: '11', text: 'Meru Githongo' },
    { id: '12', text: 'Nanyuki' },
    { id: '13', text: 'Naro Moru' },
    { id: '14', text: 'Nkubu' },
    { id: '15', text: 'Nyahururu - Koinange' },
    { id: '16', text: 'Nyeri' },
    { id: '17', text: 'Nyeri Kingóngó' },
    { id: '18', text: 'Othaya' },
    { id: '19', text: 'Ruiri' },
    { id: '20', text: 'Timau' },
  ],

  eastern: [
    { id: '1', text: 'Kalamba' },
    { id: '2', text: 'Kathiani' },
    { id: '3', text: 'Kathonzweni' },
    { id: '4', text: 'Kibwezi' },
    { id: '5', text: 'Kikima' },
    { id: '6', text: 'Kitui' },
    { id: '7', text: 'Kwavonza' },
    { id: '8', text: 'Machakos Katoloni' },
    { id: '9', text: 'Makindu' },
    { id: '10', text: 'Masii Highway' },
    { id: '11', text: 'Masii Market' },
    { id: '12', text: 'Mbooni Kalawani' },
    { id: '13', text: 'Mbooni Tawa' },
    { id: '14', text: 'Mbumbuni' },
    { id: '15', text: 'Migwani' },
    { id: '16', text: 'Mitaboni' },
    { id: '17', text: 'Mukuyuni' },
    { id: '18', text: 'Muumandu' },
    { id: '19', text: 'Mwingi' },
    { id: '20', text: 'Ngoleni' },
    { id: '21', text: 'Nguni' },
    { id: '22', text: 'Salama' },
    { id: '23', text: 'Tala Police Post' },
    { id: '24', text: 'Tulia' },
    { id: '25', text: 'Wote-Shimo' },
  ],

  western: [
    { id: '1', text: 'Amagoro' },
    { id: '2', text: 'Bondo' },
    { id: '3', text: 'Bungoma Township' },
    { id: '4', text: 'Busia' },
    { id: '5', text: 'Chavakali' },
    { id: '6', text: 'Cheptulu' },
    { id: '7', text: 'Ekero' },
    { id: '8', text: 'Esibuye' },
    { id: '9', text: 'Harambee' },
    { id: '10', text: 'Kibabii' },
    { id: '11', text: 'Kimilili' },
    { id: '12', text: 'Luanda' },
    { id: '13', text: 'Mailisaba' },
    { id: '14', text: 'Makutano' },
    { id: '15', text: 'Malaba ' },
    { id: '16', text: 'Matunda' },
    { id: '17', text: 'Mois Bridge' },
    { id: '18', text: 'Mukumu' },
    { id: '19', text: 'Nambale' },
    { id: '20', text: 'Sabatia' },
    { id: '21', text: 'Sibanga' },
    { id: '22', text: 'Ugunja' },
    { id: '23', text: 'Webuye' },
  ],

  nakuru: [
    { id: '1', text: 'Checkpoint' },
    { id: '2', text: 'Engineer' },
    { id: '3', text: 'Ewaso Nyiro' },
    { id: '4', text: 'Free Area' },
    { id: '5', text: 'Free Hold' },
    { id: '6', text: 'Gilgil' },
    { id: '7', text: 'Kamere' },
    { id: '8', text: 'Karagita' },
    { id: '9', text: 'Kihoto' },
    { id: '10', text: 'Kinamba' },
    { id: '11', text: 'Lanet' },
    { id: '12', text: 'London Area' },
    { id: '13', text: 'Madaraka Riverside Estate' },
    { id: '14', text: 'Mai Mahiu' },
    { id: '15', text: 'Maili Kumi' },
    { id: '16', text: 'Maili Sita' },
    { id: '17', text: 'Molo' },
    { id: '18', text: 'Naivasha Municipality' },
    { id: '19', text: 'Nakuru West Kaptembo' },
    { id: '20', text: 'Narok University Way' },
    { id: '21', text: 'Narok Nyawira' },
    { id: '22', text: 'Njambini' },
    { id: '23', text: 'Njoro' },
    { id: '24', text: 'Ntulele' },
    { id: '25', text: 'Ololunga' },
    { id: '26', text: 'RVIST' },
    { id: '27', text: 'Salgaa' },
    { id: '28', text: 'South Kinangop Kwaharaka' },
    { id: '29', text: 'Suswa' },
  ],

  southrift: [
    { id: '1', text: 'Awendo' },
    { id: '2', text: 'HomaBay Sofia' },
    { id: '3', text: 'Isebania' },
    { id: '4', text: 'Itumbe' },
    { id: '5', text: 'Kendu Bay' },
    { id: '6', text: 'Keroka' },
    { id: '7', text: 'Keumbu' },
    { id: '8', text: 'Kisii Jogoo' },
    { id: '9', text: 'Menyinkwa' },
    { id: '10', text: 'Migori Nyasare' },
    { id: '11', text: 'Migori Onyalo' },
    { id: '12', text: 'Mosocho' },
    { id: '13', text: 'Nyabite' },
    { id: '14', text: 'Nyakoe' },
    { id: '15', text: 'Nyamataro' },
    { id: '16', text: 'Ogembo' },
    { id: '17', text: 'Oyugis' },
    { id: '18', text: 'Rongo' },
    { id: '19', text: 'Sondu' },
  ],

  northrift: [
    { id: '1', text: 'Brooke Centre' },
    { id: '2', text: 'Bureti' },
    { id: '3', text: 'Burnt Forest ' },
    { id: '4', text: 'Chebole' },
    { id: '5', text: 'Eldoret Action' },
    { id: '6', text: 'Eldoret Hawaii' },
    { id: '7', text: 'Eldoret Huruma' },
    { id: '8', text: 'Eldoret Jamboni' },
    { id: '9', text: 'Eldoret Langas ' },
    { id: '10', text: 'Kericho Nyagacho' },
    { id: '11', text: 'Kericho Stage' },
    { id: '12', text: 'Kipkarren' },
    { id: '13', text: 'Kisumu Carwash' },
    { id: '14', text: 'Kisumu Mamboleo' },
    { id: '15', text: 'Kisumu Manyatta' },
    { id: '16', text: 'Kisumu Nubian' },
    { id: '17', text: 'Londiani' },
    { id: '18', text: 'Mosoriot' },
    { id: '19', text: 'Muhoroni' },
    { id: '20', text: 'Total Junction' },
    { id: '21', text: 'Turbo' },
  ],
};

export default regions;
